function runTest() {
function f(){return"exception!"}throw f();

  return "Exception thrown";
}
