// throw0.js
throw "exception!"