function runTest() {
  // throw0.js
  throw "exception!"

  return "Exception thrown";
}
