// throw2.js
function f() {
  return "exception!";
}
throw f()