// throw1.js
function f() {
  throw "exception!";
}
f()
