function runTest() {
  // throw1.js
  function f() {
    throw "exception!";
  }
  f()

  return "Exception thrown";
}
